---
plugin: aws_ec2
boto_profile: default
regions:
  - eu-west-3
keyed_groups:
   - key: tags
     prefix: tag
   - key: tags.Name
     separator: ''
filters:
  tag:env: dev
  instance-state-name: running
