---
- name: configure webserver
  hosts: webserver_ec2
  become: true
  gather_facts: false

  tasks:

    - name: ensure nginx is at the latest version
      apt: 
        name: nginx 
        state: latest

    - name: start nginx
      service:
          name: nginx
          state: started
          enabled: true